### ISSUE TITLE
I'm getting Compile error: Type mismatch

### ISSUE THREAD

**Issue by jackielii** [EagleAglow/vba-websocket#1]
It seems to be complaining on:

```
hSessionHandle = WinHttpOpen(StrPtr(AgentHeader), WINHTTP_ACCESS_TYPE_DEFAULT_PROXY, 0, 0, 0)
```

declaration:

```
Public Declare PtrSafe Function WinHttpOpen Lib "winhttp" ( _
   ByVal pszAgentW As LongPtr, _
   ByVal dwAccessType As Long, _
   ByVal pszProxyW As LongPtr, _
   ByVal pszProxyBypassW As LongPtr, _
   ByVal dwFlags As Long _
   ) As LongPtr
```

And it gives error: Compile error: Type mismatch

**Comment by EagleAglow** [comment]
Do you have Dim hSessionHandle As LongPtr? Is AgentHeader a string? Those are the things I think would stop the compiler.

**Comment by jackielii** [comment]
Hi @EagleAglow , thanks for your reply, I managed to work it out after reading docs and much guessing. It turns out the definition of `hSessionHandle` should be `Dim hSessionHandle As LongPtr` not `Dim hSessionHandle As Long`. There are a few more places like this. Now I'm getting `Code needs to be 101, ending...`. At least I've got it running :)

**Comment by EagleAglow** [comment]
All good, carry on :)
